use crate::toolbox::commitment::{PedersenParams};
use ark_ec::CurveGroup;

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Openings<C: CurveGroup> {
    pub zeta: Vec<C::ScalarField>,
    pub eta: Vec<C::ScalarField>,
    pub hat_t: C::ScalarField,
    pub taux: C::ScalarField,
    pub mu: C::ScalarField,
    pub fs: C::ScalarField,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RangeProof<C: CurveGroup> {
    // the intermediate commitment vector generated along the proving
    pub commitments: Vec<C>,
    // the opening vector generated along the proving
    pub openings: Openings<C>,
    // the challenge vector generated by merlin transcript
    pub challenges: Vec<C::ScalarField>,
    // the digest of the message
    pub digest: String,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RangeProofParams<C: CurveGroup> {
    // the number of witness elements
    pub num_witness: usize,
    // the number of public inputs (commitments)
    pub num_pub_inputs: usize,
    // the generators for commitments
    pub com_parameters: Vec<PedersenParams<C>>,
    // public key vector
    pub com_value: Vec<C::Affine>,
}