use crate::toolbox::commitment::{PedersenParams};
use ark_ec::CurveGroup;
use crate::bulletproofs::structs::InnerProductProof;

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Openings<C: CurveGroup> {
    pub lx: Vec<C::ScalarField>,
    pub rx: Vec<C::ScalarField>,
    pub hat_t: C::ScalarField,
    pub taux: C::ScalarField,
    pub mu: C::ScalarField,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct LinearRangeProof<C: CurveGroup> {
    // the intermediate commitment vector generated along the proving
    pub commitments: Vec<C>,
    // the opening vector generated along the proving
    pub openings: Openings<C>,
    // the challenge vector generated by merlin transcript
    pub challenges: Vec<C::ScalarField>,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct LogarithmicRangeProof<C: CurveGroup> {
    // the intermediate commitment vector generated along the proving
    pub commitments: Vec<C>,
    // the opening vector generated along the proving
    pub openings: Openings<C>,
    // the challenge vector generated by merlin transcript
    pub challenges: Vec<C::ScalarField>,
    // the Bulletproofs compression proof
    pub compression_proof: InnerProductProof<C>,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RangeProofParams<C: CurveGroup> {
    // the number of witness elements
    pub num_witness: usize,
    // the maximum size of a value
    pub supported_size: usize,
    // the generators for commitments
    pub com_parameters: Vec<PedersenParams<C>>,
    // public key vector
    pub com_value: Vec<C::Affine>,
}