[package]
name = "bulletproofs"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-secp256k1 = "0.4.0"
ark-std = { version = "0.4.0", features = ["print-trace"]}
ringsignature = { path = "../ringsignature" }
